# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jikko
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dispo-py

provider:
  name: aws
  runtime: python3.12
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:us-east-1:652276263254:table/Productos


functions:
  getProducto:
    handler: handler.lambda_handler
    events:
      - http:
          path: producto/{id}
          method: get